# Generated by Django 4.2.3 on 2024-02-10 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Narwhal_Tutoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('tutor', models.BooleanField(default=False)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('atar', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('available', models.BooleanField(blank=True, default=True)),
                ('pfp_url', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='Narwhal_Tutoring.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
