# Generated by Django 4.2.3 on 2024-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narwhal_Tutoring', '0004_alter_user_details_address_alter_user_details_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='claimed_discount',
            field=models.BooleanField(default=False),
        ),
    ]
